"""
Tool Executor — calls Module 1 (MCP Data Server) REST endpoints.

Executes tool-call plans generated by the planner against the
FleetDataService running on port 8002.
"""

import asyncio
import time
from typing import Any

import httpx

MCP_SERVER_BASE_URL = "http://localhost:8002"

# Map tool names to their REST endpoint paths and HTTP methods
TOOL_ENDPOINTS = {
    "get_expenses": {"method": "GET", "path": "/tools/expenses"},
    "get_revenue": {"method": "GET", "path": "/tools/revenue"},
    "get_truck_profit": {"method": "GET", "path": "/tools/profit"},
    "find_document": {"method": "GET", "path": "/tools/documents"},
    "resolve_entity": {"method": "GET", "path": "/tools/entity/resolve"},
    "get_upcoming_renewals": {"method": "GET", "path": "/tools/renewals"},
    "get_fleet_overview": {"method": "GET", "path": "/tools/fleet-overview"},
}


async def execute_single_tool(
    client: httpx.AsyncClient, tool_name: str, params: dict[str, Any]
) -> dict[str, Any]:
    """Execute a single tool call against the MCP Data Server."""
    endpoint = TOOL_ENDPOINTS.get(tool_name)
    if not endpoint:
        return {"tool": tool_name, "error": f"Unknown tool: {tool_name}", "execution_time_ms": 0}

    start = time.perf_counter()
    try:
        if endpoint["method"] == "GET":
            # Filter out None values from params
            query_params = {k: v for k, v in params.items() if v is not None}
            response = await client.get(
                f"{MCP_SERVER_BASE_URL}{endpoint['path']}",
                params=query_params,
                timeout=10.0,
            )
        else:
            response = await client.post(
                f"{MCP_SERVER_BASE_URL}{endpoint['path']}",
                json=params,
                timeout=10.0,
            )

        elapsed_ms = int((time.perf_counter() - start) * 1000)
        response.raise_for_status()
        return {
            "tool": tool_name,
            "params": params,
            "result": response.json(),
            "execution_time_ms": elapsed_ms,
        }
    except httpx.HTTPStatusError as e:
        elapsed_ms = int((time.perf_counter() - start) * 1000)
        return {
            "tool": tool_name,
            "params": params,
            "error": f"HTTP {e.response.status_code}: {e.response.text[:200]}",
            "execution_time_ms": elapsed_ms,
        }
    except httpx.RequestError as e:
        elapsed_ms = int((time.perf_counter() - start) * 1000)
        return {
            "tool": tool_name,
            "params": params,
            "error": f"Connection error: {str(e)[:200]}",
            "execution_time_ms": elapsed_ms,
        }


async def execute_tool_plan(plan: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """
    Execute a list of tool calls in parallel against the MCP Data Server.

    Args:
        plan: List of {"tool": "tool_name", "params": {...}} dicts

    Returns:
        List of execution results with tool name, params, result/error, and timing.
    """
    async with httpx.AsyncClient() as client:
        tasks = [
            execute_single_tool(client, call["tool"], call.get("params", {}))
            for call in plan
        ]
        results = await asyncio.gather(*tasks)
    return list(results)
